# Generated by Django 5.2.1 on 2025-05-19 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.PositiveIntegerField()),
                ('repo_name', models.CharField(max_length=255)),
                ('repo_url', models.URLField()),
                ('repo_description', models.TextField(blank=True, null=True)),
                ('repo_language', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_repos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'repo_id')},
            },
        ),
    ]
